INSERT INTO informacao_pousada VALUES ('Pousada Quinta do Ypuã', 'Estrada Ipua, nº 6', 'Laguna - SC', '88790-000', '(48) 99940-9732', 'pousadaquintadoypua@gmail.com', 'https://www.quintadoypua.com', 'https://www.facebook.com/pousadaquintadoypua', 'https://www.instagram.com/pousadaquintadoypua/', '+55 48 99940-9732');

INSERT INTO acomodacao VALUES (1, 1, 'Suíte com Cozinha', 300.00, 'Acomoda: 3', 'Camas: 1 Solteiro, 1 Casal', 'Obs: Os valores exibidos no site estão sujeitos a constantes atualizações. Para mais detalhes entre em contato por telefone. Com ampla vista para o mar, esta acomodação possui cama de casal, cama extra, ar-condicionado e TV, além de possuir também uma pequena cozinha com utensílios básicos e banheiro. Na sua parte externa possui deck com churrasqueira. A acomodação é ideal para duas pessoas, podendo comportar até três. (Arraste a imagem de capa para o lado para ver mais fotos da acomodação)', 'Ar condicionado, WiFi, TV, Cozinha, Toalhas', 'Mínimo de noites: 2');

INSERT INTO acomodacao VALUES (2, 2, 'Chalé Família', 500.00, 'Acomoda: 5', 'Camas: 1 Solteiro, 2 Casal', 'Obs: Os valores exibidos no site estão sujeitos a constantes atualizações. Para mais detalhes entre em contato por telefone. Esta acomodação possui dois quartos, um dos quartos com cama de casal e TV e o outro com cama de casal e uma de solteiro. Ambos os quartos são equipados com ar-condicionado. Possui também banheiro, cozinha com utensílios básicos e churrasqueira. Na sua parte externa possui sacada com ampla vista para o mar. A acomodação é ideal para até cinco pessoas. (Arraste a imagem de capa para o lado para ver mais fotos da acomodação)', 'Ar condicionado, WiFi, TV, Cozinha, Toalhas', 'Mínimo de noites: 2');

INSERT INTO acomodacao VALUES (3, 3, 'Cabana', 400.00, 'Acomoda: 3', 'Camas: 1 Solteiro, 1 Casal', 'Obs: Os valores exibidos no site estão sujeitos a constantes atualizações. Para mais detalhes entre em contato por telefone. Esta acomodação está localizada em uma área mais reservada da pousada. Possui cama de casal, uma cama de solteiro, cama extra, ar-condicionado, TV, cozinha com utensílios básicos e banheiro. Na área externa possui varanda e deck com churrasqueira, tendo ampla vista para o mar. A acomodação é ideal para três pessoas, podendo comportar até quatro. (Arraste a imagem de capa para o lado para ver mais fotos da acomodação)', 'Ar condicionado, WiFi, TV, Cozinha, Toalhas', 'Mínimo de noites: 2');

INSERT INTO acomodacao VALUES (4, 4, 'Bus', 425.00, 'Acomoda: 2', 'Camas: 1 Casal', 'Obs: Os valores exibidos no site estão sujeitos a constantes atualizações. Nos feriados e datas comemorativas o valor da diária também é diferenciado. Para mais detalhes entre em contato por telefone. Bus é a grande novidade da pousada. A seguir alguns detalhes que acompanham esta acomodação especial: Roupas de cama; Roupas de banho; Banheira de hidromassagem; Cozinha básica; Taças; Churrasqueira; Televisão; Soundbar Jbl Cinema; Cafeteira com cápsula; Rede de descanso; Área com vista para o mar; Deck externo com fogueira; Acompanha uma cesta de café da manhã; (Arraste a imagem de capa para o lado para ver mais fotos da acomodação)', 'Ar condicionado, WiFi, TV, Frigobar, Ducha, Banheira, Cozinha, Toalhas', 'Mínimo de noites: 2');

INSERT INTO acomodacao VALUES (5, 5, 'Estacionamento Para Overlands', 100.00, 'Acomoda: 4', ' ', 'Obs: Os valores exibidos no site estão sujeitos a constantes atualizações. Para mais detalhes entre em contato por telefone. A pousada conta também com um espaço plano com vista para o mar, destinado a estacionamento de overlands, tendo disponível para uso ponto de água e luz. Possui também banheiro e churrasqueira para uso comum destes viajantes. (Arraste a imagem de capa para o lado para ver mais fotos da acomodação)', 'WiFi, Ducha', 'Mínimo de noites: 2');